# Generated by Django 3.1.4 on 2020-12-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=64)),
                ('level', models.IntegerField()),
                ('promoted', models.BooleanField()),
                ('origin', models.CharField(max_length=32)),
                ('affinity', models.CharField(choices=[('FI', 'FIRE'), ('WA', 'WATER'), ('EA', 'EARTH'), ('WI', 'WIND'), ('TH', 'THUNDER'), ('IC', 'ICE'), ('LI', 'LIGHT'), ('DA', 'DARK'), ('VO', 'VOID'), ('NU', 'NULL')], max_length=2)),
                ('boon', models.CharField(choices=[('HP', 'HP'), ('STR', 'STRENGTH'), ('MAG', 'MAGIC'), ('SKL', 'SKILL'), ('SPD', 'SPEED'), ('LCK', 'LUCK'), ('DEF', 'DEFENSE'), ('RES', 'RESISTANCE'), ('CON', 'CONSTITUTION')], max_length=3)),
                ('bane', models.CharField(choices=[('HP', 'HP'), ('STR', 'STRENGTH'), ('MAG', 'MAGIC'), ('SKL', 'SKILL'), ('SPD', 'SPEED'), ('LCK', 'LUCK'), ('DEF', 'DEFENSE'), ('RES', 'RESISTANCE'), ('CON', 'CONSTITUTION')], max_length=3)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_name', models.CharField(max_length=32)),
                ('bot_name', models.CharField(max_length=128)),
                ('weapon_type', models.CharField(choices=[('SW', 'Sword'), ('LA', 'Lance'), ('AX', 'Axe'), ('BO', 'Bow'), ('FI', 'Fire'), ('TH', 'Thunder'), ('WI', 'Wind'), ('LI', 'Light'), ('DA', 'Dark'), ('ST', 'Staff'), ('DS', 'Dragonstone'), ('DG', 'Dagger'), ('TO', 'Tool'), ('OH', 'Offhand'), ('SH', 'Shield'), ('CH', 'Charm'), ('RI', 'Ring'), ('EQ', 'Equipment')], max_length=2)),
                ('subtype', models.CharField(choices=[('SW', 'Sword'), ('LA', 'Lance'), ('AX', 'Axe'), ('BO', 'Bow'), ('FI', 'Fire'), ('TH', 'Thunder'), ('WI', 'Wind'), ('LI', 'Light'), ('DA', 'Dark'), ('ST', 'Staff'), ('DS', 'Dragonstone'), ('DG', 'Dagger'), ('TO', 'Tool'), ('OH', 'Offhand'), ('SH', 'Shield'), ('CH', 'Charm'), ('RI', 'Ring'), ('EQ', 'Equipment')], max_length=2)),
                ('rank', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('might', models.IntegerField(default=-256)),
                ('weight', models.IntegerField(default=-256)),
                ('hit', models.IntegerField(default=-256)),
                ('crit', models.IntegerField(default=-256)),
                ('rng_min', models.IntegerField(default=0)),
                ('rng_max', models.IntegerField(default=0)),
                ('uses', models.PositiveIntegerField(default=1)),
                ('other', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.charactersheet')),
            ],
        ),
    ]
