# Generated by Django 3.1.4 on 2020-12-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0002_auto_20201214_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersheet',
            name='date_created',
        ),
    ]
