# Generated by Django 3.1.4 on 2020-12-14 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0003_remove_charactersheet_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='affinity',
            field=models.CharField(choices=[('FI', 'FIRE'), ('WA', 'WATER'), ('EA', 'EARTH'), ('WI', 'WIND'), ('TH', 'THUNDER'), ('IC', 'ICE'), ('LI', 'LIGHT'), ('DA', 'DARK'), ('VO', 'VOID')], max_length=2),
        ),
    ]
