# Generated by Django 3.1.4 on 2020-12-15 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charsheet', '0004_auto_20201214_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='epithet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='prf',
            field=models.BooleanField(default=False),
        ),
    ]
