# Generated by Django 3.1.4 on 2020-12-15 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0005_auto_20201214_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('promoted', models.BooleanField(default=False)),
                ('hp', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('magic', models.IntegerField(default=0)),
                ('skill', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('resistance', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='charactersheet',
            name='promoted',
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('magic', models.IntegerField(default=0)),
                ('skill', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('resistance', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.charactersheet')),
            ],
        ),
        migrations.CreateModel(
            name='Growths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('strength', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('magic', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('skill', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('speed', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('luck', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('defense', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('resistance', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('constitution', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.charactersheet')),
            ],
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.role'),
        ),
    ]
