# Generated by Django 3.1.4 on 2020-12-15 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0007_auto_20201214_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Growths',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
