# Generated by Django 3.1.4 on 2020-12-15 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0009_auto_20201214_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Growths',
            new_name='Growth',
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
    ]
