# Generated by Django 3.1.4 on 2020-12-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0011_auto_20201215_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='block',
            field=models.IntegerField(default=-256),
        ),
        migrations.AddField(
            model_name='equipment',
            name='block_dr',
            field=models.IntegerField(default=-256),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='other',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='subtype',
            field=models.CharField(choices=[('SW', 'Sword'), ('LA', 'Lance'), ('AX', 'Axe'), ('BO', 'Bow'), ('FI', 'Fire'), ('TH', 'Thunder'), ('WI', 'Wind'), ('LI', 'Light'), ('DA', 'Dark'), ('ST', 'Staff'), ('DS', 'Dragonstone'), ('DG', 'Dagger'), ('TO', 'Tool'), ('OH', 'Offhand'), ('SH', 'Shield'), ('CH', 'Charm'), ('RI', 'Ring'), ('EQ', 'Equipment'), ('NO', 'None')], max_length=2),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weapon_type',
            field=models.CharField(choices=[('SW', 'Sword'), ('LA', 'Lance'), ('AX', 'Axe'), ('BO', 'Bow'), ('FI', 'Fire'), ('TH', 'Thunder'), ('WI', 'Wind'), ('LI', 'Light'), ('DA', 'Dark'), ('ST', 'Staff'), ('DS', 'Dragonstone'), ('DG', 'Dagger'), ('TO', 'Tool'), ('OH', 'Offhand'), ('SH', 'Shield'), ('CH', 'Charm'), ('RI', 'Ring'), ('EQ', 'Equipment'), ('NO', 'None')], max_length=2),
        ),
    ]
